// AUTO-GENERATED by bundle.py — do not edit directly.
// Generated: 2026-05-03 14:03:21
// Run `python bundle.py` to regenerate after editing markdown files.

var CATALOG = {
  "meta": {
    "generated": "2026-05-03T14:03:21",
    "counts": {
      "source_systems": 4,
      "delivery_mechanisms": 3,
      "etl_processes": 3,
      "sources": 5,
      "processes": 3,
      "reports": 5,
      "edges": 22
    }
  },
  "sourceSystems": [
    {
      "id": "sys_finance_erp",
      "type": "source_system",
      "subtype": "ERP",
      "label": "Finance ERP",
      "owner": "Finance IT",
      "updated": "2026-01-20",
      "docs": "## Finance ERP\n\nSAP-based ERP system used by the Finance team for general ledger, accounts payable/receivable, and P&L reporting.\n\n**Platform:** SAP S/4HANA\n**Export Method:** Scheduled SFTP export (CSV)\n**Team:** Finance IT\n\n### Data Exported\n\n- P&L summary by cost center and period\n- Budget vs. actuals\n- Departmental expense allocations\n\n### Export Schedule\n\nMonthly export runs on the 2nd of each month at 00:00 UTC, covering the prior month close.\n\n### Notes\n\n- Finance IT must approve any changes to the export format or schedule\n- Budget figures require Finance sign-off before inclusion in reports"
    },
    {
      "id": "sys_hris",
      "type": "source_system",
      "subtype": "ERP",
      "label": "HR Information System",
      "owner": "HR IT",
      "updated": "2026-02-10",
      "docs": "## HR Information System\n\nEnterprise HRIS used to manage employee records, organizational structure, and payroll data.\n\n**Platform:** Workday\n**Integration Method:** SQL replication to data warehouse\n**Team:** HR IT\n\n### Data Exported\n\n- Employee master records (name, department, title, hire date, termination date)\n- Organizational hierarchy\n- Payroll summary (no PII salary data)\n\n### Refresh Cadence\n\nFull nightly refresh. Changes are captured via a Workday report export to SFTP and loaded via SSIS."
    },
    {
      "id": "sys_order_mgmt",
      "type": "source_system",
      "subtype": "ERP",
      "label": "Order Management System",
      "owner": "Operations",
      "updated": "2026-01-15",
      "docs": "## Order Management System\n\nInternal order management platform that captures all customer orders, line items, and fulfillment events.\n\n**Platform:** Custom .NET application (hosted on-prem)\n**Database:** SQL Server 2019 (PROD-SQL-01)\n**Team:** Operations Engineering\n\n### Tables Populated\n\n- `dbo.Orders` — master order header records\n- `dbo.Customers` — customer master data\n\n### Data Volume\n\n~2,000 new orders per day; ~500,000 customers total (growing ~5% YoY).\n\n### Notes\n\n- Orders table is append-only; cancellations are recorded as status updates\n- Customer data occasionally has duplicates — deduplication handled downstream in ETL"
    },
    {
      "id": "sys_salesforce",
      "type": "source_system",
      "subtype": "CRM",
      "label": "Salesforce CRM",
      "owner": "Sales Ops",
      "updated": "2026-03-05",
      "docs": "## Salesforce CRM\n\nSalesforce instance used by the Sales and Account Management teams for pipeline tracking and customer relationship management.\n\n**Edition:** Enterprise\n**Instance:** `https://yourorg.salesforce.com`\n**Auth:** OAuth 2.0 (client credentials, KeyVault-managed)\n**Team:** Sales Ops\n\n### Objects Consumed\n\n| Object      | Pull Method | Frequency    |\n|-------------|-------------|--------------|\n| Opportunity | REST API    | Incremental  |\n| Account     | REST API    | Full nightly |\n| Activity    | REST API    | Incremental  |\n\n### Notes\n\n- Connected App managed by Sales Ops — notify before credential rotation\n- API limits: 100,000 calls / 24hr rolling window"
    }
  ],
  "deliveryMechanisms": [
    {
      "id": "dlv_api_pull",
      "type": "delivery_mechanism",
      "subtype": "API Pull",
      "label": "REST API Pull",
      "owner": "Data Engineering",
      "updated": "2026-03-10",
      "docs": "## REST API Pull\n\nScheduled REST API calls to Salesforce to incrementally pull CRM data into the data pipeline.\n\n**Method:** Salesforce REST API v57.0\n**Auth:** OAuth 2.0 client credentials\n**Credentials:** KeyVault — `crm-api-prod-client-id` / `crm-api-prod-client-secret`\n**Orchestration:** Airflow DAG `crm_pull_nightly`\n\n### Pull Strategy\n\n- **Opportunity, Activity:** Incremental by `LastModifiedDate` (last 90 days)\n- **Account:** Full nightly refresh\n\n### Rate Limiting\n\nBulk API used for full refreshes; REST API for incremental. Stays well under the 100k/day API limit.\n\n### Notes\n\n- Credentials rotate every 90 days — check KeyVault expiry date\n- Notify Sales Ops before making changes to the connected app OAuth config"
    },
    {
      "id": "dlv_sftp",
      "type": "delivery_mechanism",
      "subtype": "SFTP",
      "label": "SFTP Export",
      "owner": "Finance IT",
      "updated": "2026-01-25",
      "docs": "## SFTP Export\n\nScheduled flat-file export from the Finance ERP to a secure SFTP server, picked up nightly by the data pipeline.\n\n**Server:** `sftp.internal.corp.com:/finance/exports/`\n**Auth:** SSH key (managed by Finance IT)\n**Format:** CSV, pipe-delimited, UTF-8\n**Schedule:** 2nd of each month at 01:00 UTC (monthly close file)\n\n### Files Exported\n\n| Filename Pattern             | Contents                    |\n|------------------------------|-----------------------------|\n| `pl_summary_YYYYMM.csv`      | P&L summary by cost center  |\n| `budget_actuals_YYYYMM.csv`  | Budget vs. actuals detail   |\n\n### Notes\n\n- Files are retained on SFTP for 13 months then archived to cold storage\n- Finance IT must be notified if the pickup schedule changes\n- Coordinate with Finance IT for any format changes — impacts downstream reports"
    },
    {
      "id": "dlv_sql_repl",
      "type": "delivery_mechanism",
      "subtype": "Replication",
      "label": "SQL Replication",
      "owner": "Data Engineering",
      "updated": "2026-02-01",
      "docs": "## SQL Replication\n\nTransactional replication from the OLTP source databases (Order Management, HRIS) to a read replica on PROD-SQL-01.\n\n**Type:** SQL Server Transactional Replication\n**Latency:** Near real-time (~5 min lag)\n**Monitoring:** Replication Monitor on PROD-SQL-01\n\n### Tables Replicated\n\n- `dbo.Orders` — from Order Management System\n- `dbo.Customers` — from Order Management System\n- `dbo.Employees` — from HRIS (via Workday export + SSIS)\n\n### Notes\n\n- Replication occasionally lags during peak order volumes (end of month)\n- Alert triggers if lag exceeds 30 minutes — see `#data-alerts` Slack channel\n- Schema changes on source require replication re-initialization — coordinate with Data Engineering"
    }
  ],
  "etlProcesses": [
    {
      "id": "etl_crm_pull",
      "type": "etl_process",
      "subtype": "Python",
      "label": "CRM API Ingestion",
      "owner": "Data Engineering",
      "updated": "2026-03-15",
      "docs": "## CRM API Ingestion\n\nPython script that calls the Salesforce REST API, transforms the CRM data, and stages it in the reporting warehouse for downstream consumption.\n\n**Script:** `/pipelines/crm/crm_ingestion.py`\n**Orchestration:** Airflow DAG `crm_pull_nightly`\n**Schedule:** Daily at 01:30 UTC\n**Avg runtime:** ~12 minutes\n\n### Steps\n\n1. Authenticate to Salesforce via OAuth 2.0\n2. Pull incremental Opportunity and Activity data (last 90 days)\n3. Full refresh Account data\n4. Normalize and flatten nested JSON fields\n5. Load into `warehouse.dbo.CRMStaging` (truncate + reload for accounts; upsert for opportunities)\n6. Publish run metrics to Airflow XCom\n\n### Notes\n\n- Credential rotation required every 90 days — see KeyVault `crm-api-prod-*` secrets\n- Rate limit monitoring built into the script; backs off automatically if within 10% of limit"
    },
    {
      "id": "etl_fin_load",
      "type": "etl_process",
      "subtype": "SSIS",
      "label": "Finance File Load",
      "owner": "Data Engineering",
      "updated": "2026-02-15",
      "docs": "## Finance File Load\n\nSSIS package that picks up the monthly Finance ERP export from SFTP and loads it into the reporting warehouse.\n\n**Package:** `\\ETL\\FinanceMonthlyLoad.dtsx`\n**Server:** SQL Server Agent on PROD-SQL-01\n**Schedule:** 2nd of each month at 03:00 UTC (after SFTP export arrives)\n**Avg runtime:** ~3 minutes\n\n### Steps\n\n1. Check SFTP for `pl_summary_YYYYMM.csv` and `budget_actuals_YYYYMM.csv`\n2. Validate file structure and row count against prior month (within 20% variance)\n3. Load P&L data into `warehouse.dbo.PLFact`\n4. Load budget data into `warehouse.dbo.BudgetFact`\n5. Archive processed files to `/finance/exports/processed/`\n\n### Error Handling\n\nOn failure: SQL Agent alert to `data-eng@corp.com` and Finance IT. Manual review required before re-run — Finance must confirm file is correct.\n\n### Notes\n\n- If Finance ERP export is late, this job will fail gracefully and can be re-triggered manually once the file arrives"
    },
    {
      "id": "etl_sales_hr_load",
      "type": "etl_process",
      "subtype": "SSIS",
      "label": "SSIS Sales & HR Load",
      "owner": "Data Engineering",
      "updated": "2026-03-01",
      "docs": "## SSIS Sales & HR Load\n\nSQL Server Integration Services (SSIS) package that validates and loads replicated sales and HR records into the reporting-ready tables on PROD-SQL-01.\n\n**Package:** `\\ETL\\SalesHR_NightlyLoad.dtsx`\n**Server:** SQL Server Agent on PROD-SQL-01\n**Schedule:** Daily at 01:00 UTC\n**Avg runtime:** ~8 minutes\n\n### Steps\n\n1. Validate referential integrity between Orders and Customers\n2. Cleanse and deduplicate Customer records\n3. Apply SCD Type 2 logic for customer dimension changes\n4. Load `warehouse.dbo.CustomerDim` and `warehouse.dbo.OrderFact`\n5. Load `warehouse.dbo.EmployeeDim` from HRIS replication\n6. Update pipeline audit log\n\n### Error Handling\n\nOn failure: SQL Server Agent alert emails `data-eng@corp.com`. Does not auto-retry — manual intervention required after root-cause review."
    }
  ],
  "sourceTree": [
    {
      "id": "srv_prod_sql_01",
      "type": "server_group",
      "label": "PROD-SQL-01",
      "owner": "DBA Team",
      "updated": "2026-04-01",
      "docs": "## PROD-SQL-01\n\nPrimary SQL Server instance hosting all operational and reporting databases.\n\n**Version:** SQL Server 2022 (16.0.4105)\n**Host:** prod-sql-01.internal.corp\n**Environment:** Production\n\n### Access\n\nRead access for reporting is granted via the `rpt_readonly` service account. Submit a ticket to the DBA team for access requests.\n\n### Maintenance Windows\n\nPlanned maintenance occurs the **first Sunday of each month, 01:00–04:00 UTC**. Schedule-sensitive reports should account for potential unavailability.\n\n### Monitoring\n\nServer health is monitored via Datadog. Alert threshold: CPU > 80% for 5 min, disk < 10% free.",
      "databases": [
        {
          "id": "db_humanresources",
          "type": "database_group",
          "label": "HumanResources",
          "owner": "IT Ops",
          "updated": "2026-03-15",
          "docs": "## HumanResources\n\nEmployee and organizational structure data. Contains PII — access is **restricted**.\n\n**Access policy:** Query only via approved stored procedures. Direct table access requires VP-level approval and is logged.\n\n### PII Classification\n\nThis database contains personal data under GDPR Article 9. Do not export employee data to unencrypted destinations. All report outputs containing PII must be classified accordingly.\n\n### Schema\n\nProduction tables are in the `dbo` schema. Historical snapshots are in the `archive` schema.",
          "tables": [
            {
              "id": "tbl_employees",
              "type": "source",
              "subtype": "Table",
              "label": "dbo.Employees",
              "owner": "IT Ops",
              "updated": "2026-03-15",
              "docs": "## dbo.Employees\n\nEmployee master table. Do not query directly — use `sp_HRSummary` or approved reporting views.\n\n**Rows:** ~1,800\n\n### Key Columns\n\n| Column | Type | Notes |\n|---|---|---|\n| `EmployeeID` | INT | Primary key |\n| `DepartmentID` | INT | FK → dbo.Departments |\n| `HireDate` | DATE | |\n| `TermDate` | DATE | NULL if active |\n| `JobLevel` | INT | 1–7 |\n| `IsActive` | BIT | Computed from TermDate |\n\n### Access Reminder\n\n⚠️ This table contains salary and personal data. All queries are audit-logged. Access is via `sp_HRSummary` only for report developers."
            }
          ]
        },
        {
          "id": "db_salesoltp",
          "type": "database_group",
          "label": "SalesOLTP",
          "owner": "DBA Team",
          "updated": "2026-04-01",
          "docs": "## SalesOLTP\n\nCore transactional sales database. The read replica is used for all reporting workloads — do not query the primary for reports.\n\n**Primary:** prod-sql-01.internal.corp\\SalesOLTP\n**Read Replica:** prod-sql-01.internal.corp\\SalesOLTP_RO\n**Collation:** SQL_Latin1_General_CP1_CI_AS\n\n### Refresh Cadence\n\nThe read replica syncs every **15 minutes** via log shipping. Real-time data should not be expected.\n\n### Schema Notes\n\nAll production tables live in the `dbo` schema. The `staging` schema is used for ETL intermediate loads and should not be queried directly in reports.",
          "tables": [
            {
              "id": "tbl_customers",
              "type": "source",
              "subtype": "Table",
              "label": "dbo.Customers",
              "owner": "DBA Team",
              "updated": "2026-02-14",
              "docs": "## dbo.Customers\n\nCustomer master table. One row per unique customer account.\n\n**Rows:** ~310,000\n\n### Key Columns\n\n| Column | Type | Notes |\n|---|---|---|\n| `CustomerID` | INT | Primary key |\n| `AccountName` | NVARCHAR(200) | Legal entity name |\n| `Segment` | VARCHAR(50) | Enterprise, Mid-Market, SMB |\n| `Region` | CHAR(3) | ISO region |\n| `IsActive` | BIT | 0 = churned, exclude from active count KPIs |\n\n### Notes\n\n- `IsActive = 0` customers are **soft-deleted** — they remain in the table for historical joins\n- Segment values are maintained by Sales Ops; changes flow in nightly from Salesforce"
            },
            {
              "id": "tbl_orders",
              "type": "source",
              "subtype": "Table",
              "label": "dbo.Orders",
              "owner": "DBA Team",
              "updated": "2026-03-20",
              "docs": "## dbo.Orders\n\nOrder header table. One row per order. Line items are in `dbo.OrderLines`.\n\n**Rows:** ~4.2M (as of 2026-03)\n**Avg daily inserts:** ~3,500\n\n### Key Columns\n\n| Column | Type | Notes |\n|---|---|---|\n| `OrderID` | INT | Primary key |\n| `CustomerID` | INT | FK → dbo.Customers |\n| `OrderDate` | DATETIME | UTC |\n| `Status` | VARCHAR(20) | Pending, Shipped, Cancelled, Returned |\n| `TotalAmount` | DECIMAL(18,2) | Gross order value, pre-discount |\n| `RegionCode` | CHAR(3) | ISO region code |\n\n### Gotchas\n\n- `TotalAmount` is **gross** — use `dbo.OrderLines.NetAmount` for net revenue figures\n- Orders with `Status = 'Cancelled'` should typically be excluded from revenue reports\n- `OrderDate` is stored in UTC; convert to local timezone for regional reports"
            }
          ]
        }
      ]
    },
    {
      "id": "src_crm_api",
      "type": "source",
      "subtype": "REST API",
      "label": "CRM API",
      "owner": "Sales Ops",
      "updated": "2026-04-10",
      "docs": "## CRM API (Salesforce)\n\nSalesforce REST API used to pull opportunity and account data into the reporting pipeline.\n\n**Base URL:** `https://yourorg.salesforce.com/services/data/v57.0/`\n**Auth:** OAuth 2.0 client credentials\n**Credentials:** KeyVault → `crm-api-prod-client-id` / `crm-api-prod-client-secret`\n\n### Objects Consumed\n\n- **Opportunity** — pipeline and closed deals; pulled for last 90 days\n- **Account** — customer account metadata; full refresh nightly\n- **Activity** — call/email logs; pulled for last 30 days\n\n### Rate Limits\n\n- 100,000 API calls per 24-hour rolling window\n- Bulk API used for full refreshes; REST API for incremental\n\n### Contact\n\nSales Ops owns the connected app configuration. Notify Sales Ops before making changes to the OAuth credentials."
    },
    {
      "id": "src_finance_export",
      "type": "source",
      "subtype": "File/CSV",
      "label": "Finance Export (SAP)",
      "owner": "Finance",
      "updated": "2026-04-28",
      "docs": "## Finance Export (SAP)\n\nMonthly CSV export from SAP ERP produced by the Finance team. This is a **manual process** — the pipeline depends on Finance dropping the file on schedule.\n\n**Path:** `\\\\fileserver\\Finance\\exports\\YYYYMM_FinanceExport.csv`\n**Format:** UTF-8, semicolon-delimited\n**Expected delivery:** By the **3rd of each month** by 09:00\n\n### Columns\n\n| Column | Notes |\n|---|---|\n| `CostCenter` | 6-digit code |\n| `GLAccount` | General ledger account |\n| `Amount` | EUR, 2dp |\n| `Period` | YYYYMM |\n| `Category` | Revenue, COGS, OpEx, etc. |\n\n### ⚠️ Failure Risk\n\nIf Finance does not deliver the file by the 3rd, `finance_load.sql` and the P&L Dashboard refresh will fail. Escalate to Finance controller if file is missing past 10:00 on the 3rd.\n\n### Historical Files\n\nPrior month files are retained in `\\\\fileserver\\Finance\\exports\\archive\\`. Do not delete."
    }
  ],
  "processes": [
    {
      "id": "proc_finance_load",
      "type": "process",
      "subtype": "SQL Script",
      "label": "finance_load.sql",
      "owner": "Finance BI",
      "updated": "2026-04-05",
      "docs": "## finance_load.sql\n\nSQL script that ingests the monthly Finance CSV export from SAP into the reporting warehouse. **Manually triggered** by Finance BI after validating the CSV file.\n\n**Path:** `/pipelines/finance/finance_load.sql`\n**Trigger:** Manual — Finance BI runs this after confirming the SAP export is complete\n**Avg runtime:** ~6 minutes\n\n### Steps\n\n1. Stage CSV into `warehouse.staging.FinanceRaw` (BULK INSERT)\n2. Validate row counts and spot-check totals against Finance's control report\n3. Truncate `warehouse.dbo.FinanceFact` for the period being loaded\n4. Transform and load from staging to fact table\n5. Update `warehouse.dbo.PipelineAudit`\n\n### Validation Checks\n\nThe script includes built-in assertions:\n- Row count > 0\n- No NULL `CostCenter` or `GLAccount`\n- Period matches the expected YYYYMM\n\nIf any check fails, the transaction is rolled back and an error is raised.\n\n### Running the Script\n\n```sql\n-- Set the period and file path before running\nDECLARE @Period CHAR(6) = '202604';\nDECLARE @FilePath NVARCHAR(500) = '\\\\fileserver\\Finance\\exports\\202604_FinanceExport.csv';\nEXEC sp_executesql ... -- see script header for full instructions\n```\n\n### ⚠️ Note\n\nDo not run for a period that has already been loaded without first confirming with Finance — the script truncates the fact table for that period."
    },
    {
      "id": "proc_sales_etl",
      "type": "process",
      "subtype": "Python",
      "label": "sales_etl.py",
      "owner": "Data Engineering",
      "updated": "2026-04-20",
      "docs": "## sales_etl.py\n\nNightly ETL pipeline. Combines transactional sales data from SQL Server with CRM opportunity data from Salesforce, enriches it, and loads into the reporting warehouse.\n\n**Path:** `/pipelines/sales/sales_etl.py`\n**Schedule:** Daily at **02:00 UTC** (Airflow DAG: `sales_nightly`)\n**Avg runtime:** 18 minutes\n**SLA:** Must complete by 04:00 UTC before business-hour reports run\n\n### Steps\n\n1. Extract orders from `dbo.Orders` (incremental, last 90 days by `OrderDate`)\n2. Extract customer data from `dbo.Customers` (full refresh)\n3. Fetch Opportunity and Account data from CRM API (incremental, last 90 days)\n4. Deduplicate and join on `CustomerID` / Salesforce `AccountExternalID`\n5. Enrich with region lookup and product taxonomy\n6. Load into `warehouse.dbo.SalesFact` (UPSERT on `OrderID`)\n7. Update pipeline audit table and log metrics\n\n### Error Handling\n\nOn failure: sends alert to **#data-alerts** Slack channel and pages on-call engineer if between 03:00–06:00 UTC. **Does not auto-retry** — manual intervention required.\n\n### Dependencies\n\n- `dbo.Orders` and `dbo.Customers` must be accessible on read replica\n- CRM API credentials must be valid (rotate every 90 days — check KeyVault expiry)\n- `warehouse.dbo.SalesFact` table must exist (DDL in `/pipelines/sales/schema/`)\n\n### Configuration\n\nAll config in `/pipelines/sales/config.yaml`. Override via environment variables prefixed `SALES_ETL_`."
    },
    {
      "id": "proc_hr_sproc",
      "type": "process",
      "subtype": "Stored Proc",
      "label": "sp_HRSummary",
      "owner": "IT Ops",
      "updated": "2026-02-10",
      "docs": "## sp_HRSummary\n\nAggregation stored procedure that transforms raw HR employee data into reporting-ready summary tables. Runs on a weekly schedule.\n\n**Database:** HumanResources\n**Object:** `dbo.sp_HRSummary`\n**Schedule:** Weekly, **Sunday 01:00 UTC** (SQL Agent Job: `HR_Weekly_Refresh`)\n**Avg runtime:** ~4 minutes\n\n### Output Tables\n\n| Table | Description |\n|---|---|\n| `reporting.dbo.HeadcountSummary` | Department-level headcount, open reqs, attrition |\n| `reporting.dbo.OrgHierarchy` | Flattened manager chain, levels 1–7 |\n\n### Logic Notes\n\n- Excludes contractors (`EmployeeType = 'Contractor'`)\n- Attrition rate = voluntary terminations only; involuntary are flagged separately\n- `OrgHierarchy` is rebuilt from scratch each run (not incremental)\n\n### ⚠️ Month-End Risk\n\nDuring month-end close (last 3 business days), avoid ad-hoc executions — the stored proc holds row-level locks and can block Finance queries on the same server.\n\n### Failure Impact\n\nIf this job fails Sunday night, Monday's **Headcount Report** will show the prior week's data. The on-call engineer should investigate and manually re-run if not resolved by Monday 06:00."
    }
  ],
  "reports": [
    {
      "id": "rpt_exec_dashboard",
      "type": "report",
      "subtype": "PowerBI",
      "label": "Executive Dashboard",
      "owner": "BI Team",
      "updated": "2026-05-01",
      "docs": "## Executive Dashboard\n\nC-suite KPI dashboard combining sales performance, headcount, and pipeline metrics. Primary report for monthly leadership review.\n\n**Workspace:** Executive Reports\n**App:** Corp Executive App (pinned to C-suite Power BI app)\n**Refresh:** Daily at 06:00 — dataset: `ExecDashboard_DS`\n**RLS:** Not applied — visible to all Executive workspace members\n\n### Pages\n\n1. **Revenue & Pipeline** — MTD, QTD, YTD revenue vs. budget; pipeline coverage ratio\n2. **Headcount & Attrition** — headcount by department, attrition trend, open reqs\n3. **Regional Breakdown** — revenue and headcount by region, drillthrough to detail\n\n### Data Sources\n\n| Source | Connection Mode | Refresh |\n|---|---|---|\n| `warehouse.dbo.SalesFact` | DirectQuery | Live |\n| `reporting.dbo.HeadcountSummary` | Import | Daily 06:00 |\n| `reporting.dbo.OrgHierarchy` | Import | Daily 06:00 |\n\n### Known Issues\n\n- **Regional Breakdown drillthrough** occasionally errors on mobile app — workaround: use browser\n- Budget variance line chart has a display issue in Safari — investigating\n\n### Change Log\n\n- **2026-05-01:** Added pipeline coverage ratio card (requested by CFO)\n- **2026-03-15:** Switched SalesFact to DirectQuery to eliminate 6hr data lag"
    },
    {
      "id": "rpt_headcount",
      "type": "report",
      "subtype": "SSRS",
      "label": "Headcount Report",
      "owner": "HR",
      "updated": "2026-03-20",
      "docs": "## Headcount Report\n\nWeekly headcount, open requisitions, and attrition summary by department. Distributed to HR Business Partners every Monday morning.\n\n**Path:** `/Reports/HR/HeadcountReport`\n**Schedule:** Weekly, Monday 08:00\n**Delivery:** Email to `hr-bp-list@corp.com`\n\n### Parameters\n\n| Parameter | Default |\n|---|---|\n| `@AsOfDate` | Most recent Sunday |\n| `@Department` | All |\n| `@IncludeContractors` | No |\n\n### Key Metrics\n\n- Active headcount by department and level\n- Week-over-week headcount change\n- Open requisitions (sourced from ATS integration)\n- 90-day rolling attrition rate (voluntary)\n- New hires and terminations in the past 30 days\n\n### ⚠️ Dependency Note\n\nThis report queries `reporting.dbo.HeadcountSummary`, which is populated by `sp_HRSummary` on Sunday nights. **If the Sunday job fails, this report will reflect the prior week's data.** Check with IT Ops before distributing if there are any data concerns."
    },
    {
      "id": "rpt_monthly_sales",
      "type": "report",
      "subtype": "SSRS",
      "label": "Monthly Sales Report",
      "owner": "Sales Ops",
      "updated": "2026-04-22",
      "docs": "## Monthly Sales Report\n\nTop-line revenue summary by region, product line, and sales rep. Delivered to Sales leadership on the first of each month.\n\n**Path:** `/Reports/Sales/MonthlySalesReport`\n**Schedule:** 1st of month, 07:00 local\n**Delivery:** Email subscription to `sales-leadership@corp.com`\n**Format:** PDF + Excel attachments\n\n### Parameters\n\n| Parameter | Default | Notes |\n|---|---|---|\n| `@Month` | Prior month | YYYYMM format |\n| `@Region` | All | Optional filter |\n| `@IncludeCancelled` | No | Whether to include cancelled orders |\n\n### Key Metrics\n\n- Gross Revenue vs. Prior Month and vs. Budget\n- Net Revenue (excludes cancellations and returns)\n- Top 10 Customers by Revenue\n- Revenue by Product Line\n- Rep Attainment vs. Quota\n\n### Notes\n\n- Revenue figures source from `warehouse.dbo.SalesFact` (populated by `sales_etl.py`)\n- If `sales_etl.py` failed the prior night, figures will be stale — check Airflow before distributing\n- Budget figures are manually maintained in the SSRS shared dataset `BudgetFY2026`"
    },
    {
      "id": "rpt_pl_dashboard",
      "type": "report",
      "subtype": "PowerBI",
      "label": "P&L Dashboard",
      "owner": "Finance BI",
      "updated": "2026-04-06",
      "docs": "## P&L Dashboard\n\nProfit & Loss view against budget. Used in the monthly CFO review and Board reporting package.\n\n**Workspace:** Finance Reports\n**Refresh:** Manual — Finance BI triggers after validating `finance_load.sql`\n**RLS:** Applied by CostCenter — users only see their own cost centers unless in the Finance group\n\n### Pages\n\n1. **Summary P&L** — Revenue, COGS, Gross Margin, OpEx, EBITDA vs. Budget\n2. **Cost Center Drill** — OpEx breakdown by cost center\n3. **Trend** — 13-month rolling view\n\n### Refresh Process\n\n1. Finance delivers SAP export CSV by 3rd of month\n2. Finance BI validates the file and runs `finance_load.sql`\n3. Finance BI manually triggers dataset refresh in Power BI Service\n4. Finance BI validates figures against the SAP control report\n5. Finance BI notifies CFO office that dashboard is ready\n\n### ⚠️ Do Not Auto-Schedule\n\nThis dataset intentionally has no scheduled refresh. Month-end figures require human validation before the CFO sees them."
    },
    {
      "id": "rpt_sales_detail",
      "type": "report",
      "subtype": "SSRS",
      "label": "Sales Detail Drillthrough",
      "owner": "Sales Ops",
      "updated": "2026-04-22",
      "docs": "## Sales Detail Drillthrough\n\nLine-item transaction detail report. Not standalone — invoked via drillthrough from the Monthly Sales Report.\n\n**Path:** `/Reports/Sales/SalesDetail`\n**Schedule:** On-demand only (no subscription)\n**Linked from:** Monthly Sales Report (click any revenue figure)\n\n### Parameters\n\n| Parameter | Passed From |\n|---|---|\n| `@Month` | Parent report |\n| `@Region` | Parent report |\n| `@CustomerID` | Drillthrough click |\n\n### Columns Shown\n\n- OrderID, OrderDate, CustomerName, Region\n- ProductLine, SKU, Quantity, UnitPrice\n- GrossAmount, DiscountAmount, NetAmount\n- OrderStatus\n\n### Notes\n\n- Maximum 10,000 rows returned; add filters if result set is large\n- Export to Excel available via the report toolbar\n- Does not support subscription delivery — interactive use only"
    }
  ],
  "edges": [
    {
      "source": "sys_order_mgmt",
      "target": "dlv_sql_repl"
    },
    {
      "source": "sys_hris",
      "target": "dlv_sql_repl"
    },
    {
      "source": "sys_salesforce",
      "target": "dlv_api_pull"
    },
    {
      "source": "sys_finance_erp",
      "target": "dlv_sftp"
    },
    {
      "source": "dlv_sql_repl",
      "target": "etl_sales_hr_load"
    },
    {
      "source": "dlv_api_pull",
      "target": "etl_crm_pull"
    },
    {
      "source": "dlv_sftp",
      "target": "etl_fin_load"
    },
    {
      "source": "etl_sales_hr_load",
      "target": "tbl_orders"
    },
    {
      "source": "etl_sales_hr_load",
      "target": "tbl_customers"
    },
    {
      "source": "etl_sales_hr_load",
      "target": "tbl_employees"
    },
    {
      "source": "etl_crm_pull",
      "target": "src_crm_api"
    },
    {
      "source": "etl_fin_load",
      "target": "src_finance_export"
    },
    {
      "source": "tbl_orders",
      "target": "proc_sales_etl"
    },
    {
      "source": "tbl_customers",
      "target": "proc_sales_etl"
    },
    {
      "source": "src_crm_api",
      "target": "proc_sales_etl"
    },
    {
      "source": "tbl_employees",
      "target": "proc_hr_sproc"
    },
    {
      "source": "src_finance_export",
      "target": "proc_finance_load"
    },
    {
      "source": "proc_sales_etl",
      "target": "rpt_monthly_sales"
    },
    {
      "source": "proc_sales_etl",
      "target": "rpt_exec_dashboard"
    },
    {
      "source": "proc_sales_etl",
      "target": "rpt_sales_detail"
    },
    {
      "source": "proc_hr_sproc",
      "target": "rpt_headcount"
    },
    {
      "source": "proc_finance_load",
      "target": "rpt_pl_dashboard"
    }
  ]
};
